## EECS 491 Assignment 3

  Yue Shu  
  Spring 2019  
  Prof. Lewicki  
  

# Exercise 1. Multivariate Gaussians

## 1.1 Consider the 2D normal distribution 

**$$ p(x,y) \sim \mathcal{N}(\mathbf{\mu}, \mathbf{\Sigma}) $$**

**Define three separate 2D covariance matrices $\mathbf{\Sigma}$ for each of the following cases: $x$ and $y$ are uncorrelated; $x$ and $y$ are correlated; and $x$ and $y$ are anti-correlated.**

The covariance matrix $\Sigma$ could be defined as below in general:

$$  
\Sigma =  \begin{bmatrix} \Sigma_{x x} & \Sigma_{x y} \\ \Sigma_{y x} & \Sigma_{y y} \end{bmatrix}
$$

### $x$ and $y$ are uncorrelated

Since $x$ and $y$ are uncorrelated, we may conclude that $\Sigma_{x y} = \Sigma_{y x} = 0$, and thus the convariance matrix should be defined as:

$$  
\Sigma =  \begin{bmatrix} var(x) & 0 \\ 0 & var(y) \end{bmatrix}
$$

### $x$ and $y$ are correlated

Since $x$ and $y$ are positively correlated, we may conclude that $\Sigma_{x y} > 0$, $\Sigma_{y x} > 0$, and thus the convariance matrix should be defined as:

$$  
\Sigma =  \begin{bmatrix} var(x) & \Sigma_{x y} \\ \Sigma_{y x} & var(y) \end{bmatrix}, \Sigma_{x y} > 0, \Sigma_{y x} > 0
$$

### $x$ and $y$ are anti-correlated

Since $x$ and $y$ are negatively correlated, we may conclude that $\Sigma_{x y} < 0$, $\Sigma_{y x} < 0$, and thus the convariance matrix should be defined as:

$$  
\Sigma =  \begin{bmatrix} var(x) & \Sigma_{x y} \\ \Sigma_{y x} & var(y) \end{bmatrix}, \Sigma_{x y} < 0, \Sigma_{y x} < 0
$$

## 1.2 Compute the principal axes for each of these distributions, i.e. the eigenvectors of the covariance matrices.

The expression of eigenvector and eigenvalue is 

$$
\mathbf{A} \mathbf{v} = \lambda \mathbf{v}
$$

### $x$ and $y$ are uncorrelated

$$
\begin{bmatrix} var(x) & 0 \\ 0 & var(y) \end{bmatrix} \mathbf{v} = \lambda \mathbf{v}
$$

$$
\begin{bmatrix} var(x) & 0 \\ 0 & var(y) \end{bmatrix} \mathbf{v} = \lambda \mathbf{v}
$$

$$
\begin{bmatrix} var(x) & 0 \\ 0 & var(y) \end{bmatrix} \begin{bmatrix} v_1 \\ v_2 \end{bmatrix} = \begin{bmatrix} \lambda v_1 \\ \lambda v_2 \end{bmatrix}
$$

$$
\begin{bmatrix} var(x) v_1 \\ var(y) v_2 \end{bmatrix}  = \begin{bmatrix} \lambda v_1 \\ \lambda v_2 \end{bmatrix}
$$

Therefore, if $var(x) \neq var(y)$, we may conclude that the eigenvector does not exist. 

However, if $var(x) = var(y)$, which means $\lambda = var(x) = var(y)$, then any vector would suffice. 

### $x$ and $y$ are correlated

The steps for positively correlated and negatively correlated $x$ and $y$ should be the same, since the only difference is the sign of the covariance, which is only represented in the actual calculations. 

$$  
\begin{bmatrix} var(x) & \Sigma_{x y} \\ \Sigma_{y x} & var(y) \end{bmatrix}  \begin{bmatrix} v_1 \\ v_2 \end{bmatrix} = \begin{bmatrix} \lambda v_1 \\ \lambda v_2 \end{bmatrix}
$$

$$
\begin{bmatrix} var(x) v_1 + \Sigma_{xy} v_2 \\ \Sigma_{yx} v_1 + var(y) v_2 \end{bmatrix}  = \begin{bmatrix} \lambda v_1 \\ \lambda v_2 \end{bmatrix}
$$

$$
\Sigma_{xy} v_2 = (\lambda - var(x)v_1)v_1
$$

$$
\Sigma_{yx}v_1 = (\lambda - var(y) v_2)v_2
$$

$$
\Sigma_{xy} v_2 = \lambda v_1 - var(x)v_1^2
$$

$$
v_2 = \frac{\lambda v_1 - var(x)v_1^2}{\Sigma_{xy}}
$$

$$
v_1 = \frac{\lambda v_2 - var(y)v_2^2}{\Sigma_{yx}}
$$

$$
v_1 = \frac{\lambda \frac{\lambda v_1 - var(x)v_1^2}{\Sigma_{xy}} - var(y)( \frac{\lambda v_1 - var(x)v_1^2}{\Sigma_{xy}})^2}{\Sigma_{yx}}
$$

After $v_1$ is solved, we just go back and solve for $v_2$. I will put a stop here since the process should be pretty trivial and in reality once we've gain the actual covariance matrix it should be pretty straight forward. 

The steps of solving for the eigenvalue $\lambda$ should also be quite simple:

$$
\Sigma - \lambda I = \begin{bmatrix} var(x) & \Sigma_{x y} \\ \Sigma_{y x} & var(y) \end{bmatrix} - \begin{bmatrix} \lambda & 0 \\ 0  &  \lambda  \end{bmatrix} = \begin{bmatrix} var(x) - \lambda & \Sigma_{xy} \\ \Sigma_{yx} & var(y) - \lambda  \end{bmatrix}
$$


Then we use the determinant to solve for the eigenvalue:

$$
var(x)var(y) + \lambda ^2 - \lambda var(x) - \lambda var(y) = \Sigma_{xy} \Sigma_{yx}
$$


$$
\lambda ^2 - ( var(x) + var(y)) \lambda - \Sigma_{xy} \Sigma_{yx} + var(x)var(y) = 0
$$

$$
\lambda_1 = \frac{var(x) + var(y) + \sqrt{( var(x) - var(y))^2 - 4 \Sigma_{xy} \Sigma_{yx}}}{2}
$$

$$
\lambda_2 = \frac{var(x) + var(y) - \sqrt{( var(x) - var(y))^2 - 4\Sigma_{xy} \Sigma_{yx}}}{2}
$$

All we should do next is to plug in the two eigenvalues, check which one is valid, and then solve for the corresponding eigenvector. Once again, I will pause my solution here since solving for the eigenvectors without any actual value is quite trivial, and as long as the steps I listed above are strictly followed, the calculation should be quite simple. 

# Exercise 2. Linear Gaussian Models (20 pts)

Consider two multi-dimensional Gaussian random vector variables

$$
\newcommand{\bm}{\mathbf}
\begin{eqnarray}
p(\bm{x}) &=& \mathcal{N}(\bm{x} | \bm{\mu_x}, \bm{\Sigma}_x) \\
p(\bm{z}) &=& \mathcal{N}(\bm{z} | \bm{\mu_z}, \bm{\Sigma}_z)
\end{eqnarray}
$$

Now consider a third variable that is the sum of the first two:

$$
\bm{y} = \bm{x} + \bm{z}
$$


## 2.1 What is the expression for the distribution $p(\bm{y})$?

First of all, assuming joint normality of $(\mathbf{x}, \mathbf{z})$, then we should have, according to the linear properties of multivariate normal random vectors,

$$
\mathbf{y} = \mathbf{A} \mathbf{x} + \mathbf{B} \mathbf{z} = (\mathbf{A} \space \space \mathbf{B})  \begin{pmatrix}
    \mathbf{x} \\  \mathbf{z}
\end{pmatrix}
$$

where both $\mathbf{A}$ and $\mathbf{B}$ are identity matrix $\mathbf{I}$.

And thus 

$$
p(\mathbf{y}) = p(\mathbf{A} \mathbf{x} + \mathbf{B} \mathbf{z}) =  \mathcal{N} (\mathbf{A} \mathbf{x} + \mathbf{B} \mathbf{y} | (\mathbf{A} \space \space \space  \mathbf{B})  \begin{pmatrix} \mathbf{\mu_x} \\ \mathbf{\mu_z} \end{pmatrix}, (\mathbf{A} \space \space \space  \mathbf{B}) \mathbf{\Sigma_{x, z} \begin{pmatrix} \mathbf{A^T} \\ \mathbf{B^T} \end{pmatrix}}
$$

Then we shall plug in $\mathbf{A} = \mathbf{B} = \mathbf{I}$, and the final expression of $p(\mathbf{y})$ would be:

$$
p(\mathbf{y}) = \mathcal{N} ( \mathbf{x} + \mathbf{z} | \mathbf{\mu_x} + \mathbf{\mu_z}, \mathbf{ \Sigma_{xx} } + \mathbf{\Sigma_{xz}^T} + \mathbf{\Sigma_{xz} } + \mathbf{ \Sigma_{zz}})
$$

## 2.2 What is the expression for the condidtional distribution $p(\bm{y|x})$?

## 2.3 Write code that simulates this data and illustrate the results.

# Exercise 3. Dimensionality Reduction and PCA

In this quesiton you will use principal component analysis to reduce the dimensionality of your data and analyze the results.

##  3.1 Find a set of high dimensional data.  It should be continuous and have at least 6 dimensions, e.g. stats for sports teams, small sound segments or images patches also work.  Note that if the dimensionality of the data is too large, you might run into computational efficiency problems using standard methods.  Describe the data and illustrate it, if appropriate.

So for this problem I will be using the breast cancer dataset retrieved from the UCI machine learning database ("http://archive.ics.uci.edu/ml/datasets/Breast+Cancer+Wisconsin+%28Diagnostic%29"). Let's first import the data and briefly take a look at it:

In [1]:
import pandas as pd

df = pd.read_csv(
    filepath_or_buffer='http://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/wdbc.data', 
    header = None, 
    sep = ',')

df.columns=['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean', 
            'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean', 
            'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean', 'radius_se', 
            'texture_se', 'perimeter_se', 'area_se', 'smoothness_se', 'compactness_se', 'concavity_se', 
            'concave points_se', 'symmetry_se', 'fractal_dimension_se', 'radius_worst', 'texture_worst', 
            'perimeter_worst', 'area_worst', 'smoothness_worst', 'compactness_worst', 'concavity_worst', 
            'concave points_worst', 'symmetry_worst', 'fractal_dimension_worst']

## drops the empty line if exist
df.dropna(how="all", inplace=True)


As we can see above, there are 32 columns in the data, where the first column is the `id` number, the second column is the label or class `diagnosis` representing the diagnosis of the breast tissues, where `B` = benign, `M` = malignant. The rest of the columns are different continuously valued attributes as described by the column headers above. A more detailed description on the attributes of the dataset can also be found from the source link I previously provided. 

To make better sense of how the diagnosis results are related to the attributes, we might visualize the attributes with histograms as below. 

Notice that for the sake of simplicity and efficiency, we will only look at six attributes for our problem 3, which is `radius_worst`, `texture_worst`, `perimeter_worst`, `area_worst`, `smoothness_worst`, and `compactness_worst`.

In [3]:
## split the dataset into data X and class labels y, the id number will be ignored
X = df.iloc[:,22:28].values
y = df.iloc[:,1].values

In [24]:
import plotly
import plotly.plotly as py

plotly.tools.set_credentials_file(username='gentsk77', api_key='p7wUPaAgt4sO8yQvjk7o')

## plotting histograms
data = []

## muted blue for benign, brick red for malignant
colors = {'B': '#1f77b4', 'M': '#d62728'}

legend = {0:False, 1:False, 2:False, 
          3:False, 4:False, 5:True}

for col in range(6):
    for key in colors:
        trace = dict(
            type = 'histogram',
            x = list(X[y == key, col]),
            opacity = 0.75,
            xaxis = 'x%s' %(col + 1),
            marker = dict(color = colors[key]),
            name = key,
            showlegend = legend[col]
        )
        data.append(trace)

layout = dict(
    barmode = 'overlay',
    xaxis1 = dict(domain = [0, 0.14], title = 'worst radius'),
    xaxis2 = dict(domain = [0.17, 0.31], title = 'worst texture'),
    xaxis3 = dict(domain = [0.34, 0.48], title = 'worst perimeter'),
    xaxis4 = dict(domain = [0.51, 0.65], title = 'worst area'),
    xaxis5 = dict(domain = [0.68, 0.82], title = 'worst smoothness'),
    xaxis6 = dict(domain = [0.85, 1], title = 'worst compactness'),
    yaxis = dict(title = 'count'),
    title = 'Distribution of breast cancer attributes'
)

fig = dict(data = data, layout = layout)
py.iplot(fig, filename = 'data visualization')

## 3.2 Compute the principal components of the data.  Plot a few of the largest eigenvectors and interpret them in terms of how there are modeling the structure of the data.

To compute the eigenvectors of the data, we need to first have the covariance matrix. Let's start with standardizing the data as below.

In [5]:
from sklearn.preprocessing import StandardScaler
X_std = StandardScaler().fit_transform(X)

Then we shall have the covariance matrix as below

In [9]:
import numpy as np
mean_vec = np.mean(X_std, axis=0)
cov_mat = (X_std - mean_vec).T.dot((X_std - mean_vec)) / (X_std.shape[0]-1)
print('Covariance matrix \n%s' %cov_mat)

Covariance matrix 
[[1.00176056 0.36055442 0.9954574  0.98574698 0.21695572 0.47665775]
 [0.36055442 1.00176056 0.36574102 0.34645116 0.2258263  0.36146761]
 [0.9954574  0.36574102 1.00176056 0.97929918 0.23719146 0.53033975]
 [0.98574698 0.34645116 0.97929918 1.00176056 0.20951355 0.43906793]
 [0.21695572 0.2258263  0.23719146 0.20951355 1.00176056 0.56918685]
 [0.47665775 0.36146761 0.53033975 0.43906793 0.56918685 1.00176056]]


Now we shall perform an eigendecomposition as below:

In [10]:
cov_mat = np.cov(X_std.T)

eig_vals, eig_vecs = np.linalg.eig(cov_mat)

print('Eigenvectors \n%s' %eig_vecs)
print('\nEigenvalues \n%s' %eig_vals)

Eigenvectors 
[[-4.97942824e-01 -2.72489891e-01 -8.40792994e-02  8.57684507e-02
   7.20948420e-01  3.78959132e-01]
 [-2.73102692e-01  2.28015536e-01  9.29096477e-01  1.00836736e-01
  -5.95488854e-03 -2.51370999e-04]
 [-5.04104514e-01 -2.36650175e-01 -9.49259445e-02  4.93865145e-03
  -6.88397894e-01  4.54915759e-01]
 [-4.90377681e-01 -2.91513263e-01 -8.94458489e-02  1.49878619e-01
  -5.63234946e-02 -8.00570578e-01]
 [-2.28045622e-01  7.07536477e-01 -3.05247522e-01  5.94380987e-01
  -1.12294382e-02  2.82209008e-02]
 [-3.61761561e-01  4.81837130e-01 -1.39724240e-01 -7.78908837e-01
   5.48435787e-02 -8.79311954e-02]]

Eigenvalues 
[3.62371526 1.21294634 0.76985699 0.38028693 0.00413964 0.01961823]


The largest eigenvalues are already quite obvious, which are the first three with the corresponding largest eigenvectors. This typically means that the three eigenvectors bear the most information about the dataset, and thus contribute the most to the modeling of the data structure, and thus should be chosen as the principal components while we are trying to reduce the dimension of the data. 

## 3.3 Plot, in decreasing order, the cumulative percentage of variance each eigenvector accounts for as a function of the eigenvector number.  These values should be in decreasing order of the eigenvalues. Interpret these results.

We shall first have the eigenvalues and eigenvectors we just computed listed as pairs in the decreasing order so as to compute the cumulative percentage of variance in decreasing order. 

In [14]:
## have all the eigenvalues and eigenvectors listed in pairs
eig_pairs = [(np.abs(eig_vals[i]), eig_vecs[:,i]) for i in range(len(eig_vals))]

## Sort the pairs in decreasing order
eig_pairs.sort()
eig_pairs.reverse()

for p in eig_pairs:
    print(p[0])

3.623715261672426
1.21294633922263
0.7698569853011382
0.38028692695674704
0.019618229300002357
0.004139637828750932


And then we shall plot the cumulative percentage of the variance each eigenvector acccounts for as a function of the eigenvector number. 

In [23]:
tot = sum(eig_vals)
var_exp = [(i / tot) * 100 for i in sorted(eig_vals, reverse = True)]
cum_var_exp = np.cumsum(var_exp)

trace = dict(type='scatter',
            x=['eigenvector %s' %i for i in range(1,7)], 
            y=cum_var_exp)

data = [trace]

layout = dict(title='Cumulative percentage of the variance each eigenvector acccounts for',
              yaxis=dict(title='Cumulative percentage of variance'))

fig = dict(data=data, layout=layout)
py.iplot(fig, filename='cumulative percentage of variance')

Apparently, the first two principal components capture 80.5% of the variance. However, it's quite a delimma whether to drop the third principal component or not since it also individually captures almost 13% of the variance. We may make the decision in the next section while making the projection on the selected principal components. Right now we shall just pick the first two eigenvectors as our final principal components. 